[workspace]

resolver = "2"
members = ["custom_processing_unit", "data_types", "literature_search", "ucode_compiler_bridge", "ucode_compiler_dynamic", "coverage", "ucode_compiler_derive", "uefi_watchdog", "ucode_dump", "hypervisor", "xtask", "fuzzer_device","hypervisor"]
