[package]
name = "ucode_compiler_dynamic"
version = "0.1.0"
edition = "2021"

[dependencies]
data_types = { path = "../data_types", features = ["nostd"] }
num-derive = "0.4.2"
num-traits = { version = "0.2.19", default-features = false }

[build-dependencies]
itertools = "0.14.0"