[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
description = "A build and test assist program"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
ctrlc = "3.4.5"
rand = "0.8.5"