[package]
name = "performance_timing_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.96", features = ["full"] }
quote = "1.0.38"
rand = "0.9.0"

[lib]
proc-macro = true

[features]
__debug = []