[package]
name = "fuzzer_master"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", default-features = false }
tokio = { version = "1.43.0", features = ["full"] }
fuzzer_data = { path = "../fuzzer_data" }
serde_json = "1.0.139"
log = "0.4.25"
