[package]
name = "x86_perf_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.219", default-features = false, features = ["alloc", "derive"]}

[target.'cfg(any(target_arch = "x86_64", target_arch = "x86"))'.dependencies]
x86 = "0.52"
bitfield = "0.19.0"