[package]
name = "custom_processing_unit"
version = "0.1.0"
edition = "2021"

[features]
no_std = []

[dependencies]
ucode_compiler = { path = "../ucode_compiler" }

[build-dependencies]
ucode_compiler = { path = "../ucode_compiler", features = ["build"] }