[package]
name = "ucode_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = { version = "0.12.4", optional = true }
regex = { version = "1.11.0", optional = true }

[features]
build = ["dep:error-chain", "dep:regex"]